### ISSUE TITLE
Missing "zone" variable in variables.tf

### ISSUE THREAD

**Issue by alebrozzo** [GoogleCloudPlatform/terraform-dynamic-javascript-webapp#80]
Following the Jump Start Solution sample using the Terraform CLI, I got a warning regarding a missing "zone" variable. I've checked `variables.tf` and indeed it is not present there.
This variable (zone) is indicated to be added to `terraform.tfvars` in the sample steps, and the warning indicates that it can see it but it cannot use it because it does not override an existing variable, and then suggests adding the variable to `variables.tf`. I did so on the console and the warning was removed.

I apologize for not having the exact warning message, after fixing I closed the broswer and I cannot see it again.

**Comment by cklanac** [comment]
### Same issue. Here's the error:

```
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named "zone" but a value was found in file "terraform.tfvars". If you meant to use this value, add a "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide certain "global" settings to all configurations in your organization. To reduce the verbosity of these warnings, use the
│ -compact-warnings option.
```

So remove or comment out the `zones` section in the `terraform.tfvars` file. 

```tf
# Google Cloud zone where you want to deploy the solution
# Example: us-central1-a
# zone = "us-central1-a"
```

### Note to maintainers

The [Jump Start Solution: Dynamic web application with JavaScript](https://cloud.google.com/architecture/application-development/dynamic-app-javascript#configure_the_terraform_variables) tutorial prompts the user to add a zone to the `terraform.tfvars`.
